baseURL       = "https://magical.enterprises/"
languageCode  = "en-us"
title         = "Magical Enterprises"
theme         = "roxo-hugo"
summarylength = 25

# Site Menus
[menu]
  # Navbar Menus
  [[menu.nav]]
    name    = "Home"
    url     = ""
    weight  = 1
  [[menu.nav]]
    name    = "About"
    url     = "about"
    weight  = 2
  [[menu.nav]]
    name    = "Store Fronts"
    url     = "portfolio"
    weight  = 3
  [[menu.nav]]
    name    = "Blog"
    url     = "blog"
    weight  = 4
  [[menu.nav]]
    name    = "Get in touch"
    url     = "contact"
    weight  = 5

# Site Params
[params]
  logo = "images/MagicalEnterprisesLogoOnly.svg"
  logo_footer = "images/magicalenterpriseslogo_small.png"
  favicon_icon = "images/MagicalEnterprisesLogoOnly.svg"
  favicon_shortcut_icon = "images/MagicalEnterprisesLogoOnly.svg"
  custom_stylesheets = []   # [ "scss/my_1.scss", "scss/my_2.scss" ]
  dateFormat = "26 FEB 1994"
  # Meta data
  description = "Printed magic for everyday wizards."
  # author = "StaticMania"
  # Google Analitycs
  googleAnalitycsID = "Your ID"
  # We're using formspree.io for form handling, paste your formspree url below
  fabform  = "https://fabform.io/v/nGJDAdnLjk3q"

  # Contact Form
  [params.contactForm]
    placeholder_first_name        = "First Name"
    placeholder_last_name         = "Last Name"
    placeholder_email             = "Email"
    placeholder_project_type      = "Inquiry Type"
    placeholder_about_the_project = "Feedback"
    send_message                  = "Send Message"

    [[params.contactForm.projectType]]
      value = "pf"
      title  = "Product Feedback"
    [[params.contactForm.projectType]]
      value = "gf"
      title  = "General Feedback"

  # Navbar Action Button
  [params.navAction]
    status  = true
    name    = "Get in touch"
    url     = "contact"


  # Banner Section
  [params.banner]
    enable                = true
    background_image      = "images/MagicalEnterprisesLogoFull.svg"
    heading               = "Printed magic for everyday wizards."
    tagline               = "Magical Enterprises"
    primary_button        = "Our Work"
    primary_button_url    = "portfolio"
    secondary_button      = "Connect with Us"
    secondary_button_url  = "contact"

  [params.blog]
    read_more             = "read more"

  [params.portfolio]
    enable    = true
    title     = "OUR WORK"
    subtitle  = "Printed magic for everyday wizards."
    view_project = "view project"
    more_works = "MORE WORKS"
    scroll_down = "scroll down"

  [params.call_to_action]
    enable              = true
    background_image    = "images/backgrounds/contact_bg.svg"
    title               = "READY TO ENJOY OUR PRODUCTS?"
    primary_button      = "Inquiry"
    primary_button_url  = "contact"
    secondary_button    = "Not Convinced"
    secondary_button_url = "portfolio"

  [params.footer]
    params.footer.qr_print = true
    # Footer Contact Info
    [params.footer.contactInfo]
      title   = "Contact Info"
      #address = "713 Elmwood St.<br>Prior Lake, MN 55372"
      #phone   = "409-896-1444"
      email   = "info@magical.enterprises"
      # Footer Sitemap
      [params.footer.sitemap]
        title   = "Sitemap"
        [[params.footer.sitemap.link]]
          name = "About Company"
          url  = "about"
        [[params.footer.sitemap.link]]
          name = "Projects"
          url  = "portfolio"
        [[params.footer.sitemap.link]]
          name = "Blog"
          url  = "blog"
        [[params.footer.sitemap.link]]
          name = "Contact"
          url  = "contact"
      # Footer Social Media
      [params.footer.social]
        title   = "Social Media"
        [[params.footer.social.link]]
          name = "X"
          url  = "https://x.com/magicalworks"
        [[params.footer.social.link]]
          name = "Instagram"
          url  = "https://www.instagram.com/magical.enterprises"
        [[params.footer.social.link]]
          name = "TikTok"
          url  = "https://www.tiktok.com/@magical.enterprises"
      # Footer Service
      [params.footer.service]
        title       = "We help brands:"
        description = "develop design solutions<br>produce valuable cultural content<br>create fresh brand experience"
      [params.footer.back_to_top]
        description = "I want to <br> visit again"
